/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AnimeIdImport } from './routes/$animeId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AnimeIdRoute = AnimeIdImport.update({
  id: '/$animeId',
  path: '/$animeId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$animeId': {
      id: '/$animeId'
      path: '/$animeId'
      fullPath: '/$animeId'
      preLoaderRoute: typeof AnimeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$animeId': typeof AnimeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$animeId': typeof AnimeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$animeId': typeof AnimeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$animeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$animeId'
  id: '__root__' | '/' | '/$animeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeIdRoute: typeof AnimeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeIdRoute: AnimeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$animeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$animeId": {
      "filePath": "$animeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
