/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PaheAnimeIdImport } from './routes/pahe.$animeId'
import { Route as KaiAnimeIdImport } from './routes/kai.$animeId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PaheAnimeIdRoute = PaheAnimeIdImport.update({
  id: '/pahe/$animeId',
  path: '/pahe/$animeId',
  getParentRoute: () => rootRoute,
} as any)

const KaiAnimeIdRoute = KaiAnimeIdImport.update({
  id: '/kai/$animeId',
  path: '/kai/$animeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kai/$animeId': {
      id: '/kai/$animeId'
      path: '/kai/$animeId'
      fullPath: '/kai/$animeId'
      preLoaderRoute: typeof KaiAnimeIdImport
      parentRoute: typeof rootRoute
    }
    '/pahe/$animeId': {
      id: '/pahe/$animeId'
      path: '/pahe/$animeId'
      fullPath: '/pahe/$animeId'
      preLoaderRoute: typeof PaheAnimeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kai/$animeId': typeof KaiAnimeIdRoute
  '/pahe/$animeId': typeof PaheAnimeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kai/$animeId': typeof KaiAnimeIdRoute
  '/pahe/$animeId': typeof PaheAnimeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/kai/$animeId': typeof KaiAnimeIdRoute
  '/pahe/$animeId': typeof PaheAnimeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kai/$animeId' | '/pahe/$animeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kai/$animeId' | '/pahe/$animeId'
  id: '__root__' | '/' | '/kai/$animeId' | '/pahe/$animeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KaiAnimeIdRoute: typeof KaiAnimeIdRoute
  PaheAnimeIdRoute: typeof PaheAnimeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KaiAnimeIdRoute: KaiAnimeIdRoute,
  PaheAnimeIdRoute: PaheAnimeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kai/$animeId",
        "/pahe/$animeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kai/$animeId": {
      "filePath": "kai.$animeId.tsx"
    },
    "/pahe/$animeId": {
      "filePath": "pahe.$animeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
